input:
    h5ad_file: "/projects/b1038/Pulmonary/lcusick/projects/seurat_to_cellbrowser/myeloid/myeloid.h5ad"
    metadata_file: "/projects/b1038/Pulmonary/lcusick/projects/seurat_to_cellbrowser/myeloid/myeloid-metadata.csv"
    markers: "/projects/b1038/Pulmonary/lcusick/projects/seurat_to_cellbrowser/myeloid/myeloid-markers.csv"
output:
    directory: "/projects/b1038/Pulmonary/lcusick/projects/seurat_to_cellbrowser/snkmk_test"
cb_config:
    cluster_field: "leiden"
    radius: 2
sample: "myeloid"
slurm:
    account: "b1042"
    partition: "genomics-himem"
    hours: 4
    cores: 8
    mem: 100
